# Generated by Django 5.1.6 on 2025-12-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchsuggestion',
            old_name='confidence_score',
            new_name='confidence',
        ),
        migrations.RemoveField(
            model_name='matchsuggestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='matchsuggestion',
            name='status',
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchsuggestion',
            name='found_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cases.foundperson'),
        ),
        migrations.AlterField(
            model_name='matchsuggestion',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cases.missingperson'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
