# Generated by Django 5.1.6 on 2026-01-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_confidence_score_matchsuggestion_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingperson',
            old_name='approx_age',
            new_name='age',
        ),
    ]
