# Generated by Django 5.1.6 on 2026-01-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_approx_age_missingperson_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingperson',
            old_name='age',
            new_name='approx_age',
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
