# Generated by Django 5.1.6 on 2026-01-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_age_missingperson_approx_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='finder_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='approx_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
