# Generated by Django 5.1.6 on 2026-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_foundperson_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsuggestion',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
