# Generated by Django 5.1.6 on 2025-12-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('POLICE', 'Police'), ('VOLUNTEER', 'Volunteer')], max_length=20),
        ),
    ]
