# Generated by Django 5.1.6 on 2026-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('POLICE', 'Police'), ('VOLUNTEER', 'Volunteer')], default='USER', max_length=10),
        ),
    ]
